num_epochs: 50
learning_rate: 0.00001
dropout_level: 0.5
wdecay: 0.001
batch_size: 10
num_class: 4
num_class_units: 5984

layers:
  number: 1
  in_channels:
    - 9
  out_channels:
    - 16
  kernel_sizes:
    - 5
  strides:
    - 2